name: vflib
channels:
  - conda-forge
dependencies:
  - python
  - pip

# openff stuff
  - openff-toolkit
  - openff-qcsubmit
  - openff-units
  - openff-bespokefit

# misc chemistry
  - qubekit

# qcarchive
  - qcportal

# utilities
  - click
  - tqdm
  - numpy
